const adminMasterData = [
    {
        "project_id": "outgoing_call_widget",
        "date": "2026.02.04",
        "category": "update",
        "image": "index_phot/Outgoing_Call_Widget.png",
        "status": "coming",
        "project_ja": "発信電話ウィジェット",
        "project_en": "Outgoing Call Widget",
        "project_de": "Anruf-Monitor Widget",
        "project_fr": "Widget d'Appels Sortants",
        "project_es": "Widget de Llamadas Salientes",
        "title_ja": "無料通話時間の設定と「ウィジェット」の表示、有料通話の判別完了。",
        "title_en": "Completed the configuration for free call allowances, home screen widget display, and the system to identify paid (non-bundle) calls.",
        "title_de": "Die Konfiguration des Freiminuten-Limits, die Anzeige des Widgets auf dem Home-Bildschirm sowie die Identifizierung kostenpflichtiger Anrufe wurden erfolgreich implementiert.",
        "title_fr": "La configuration du forfait d'appels gratuits, l'affichage du widget sur l'écran d'accueil et le système d'identification des appels payants sont désormais terminés.",
        "title_es": "Se ha completado la configuración del límite de llamadas gratuitas, la visualización del widget en la pantalla de inicio y el sistema para identificar llamadas con costo.",
        "body_ja": "30秒単位の正確な計算とウィジェット表示で、無料通話枠の残り時間を賢く管理。",
        "body_en": "Smartly manage your remaining free call balance with accurate 30-second billing increments and a convenient home screen widget.",
        "body_de": "Verwalten Sie Ihr verbleibendes Freiminuten-Kontingent clever – mit präziser 30-Sekunden-Taktung und praktischer Anzeige direkt auf Ihrem Home-Bildschirm.",
        "body_fr": "Gérez intelligemment le solde de votre forfait d'appels gratuits grâce à un calcul précis par paliers de 30 secondes et un affichage direct sur votre écran d'accueil.",
        "body_es": "Gestione de forma inteligente el saldo restante de su plan gratuito con cálculos precisos en intervalos de 30 segundos y visualización mediante un widget en su pantalla de inicio."
    },
    {
        "project_id": "kei_applab",
        "date": "2026.02.12",
        "category": "start",
        "image": "index_phot/KEI_App_Lab.png",
        "status": "coming",
        "project_ja": "啓(KEI)AppLab",
        "project_en": "KEI AppLab",
        "project_de": "",
        "project_fr": "",
        "project_es": "",
        "title_ja": " この度、屋号として新たな一歩を踏み出し、起業することを決意いたしました。",
        "title_en": " I have officially decided to launch my own business under the trade name KEI AppLab.",
        "title_de": "",
        "title_fr": "",
        "title_es": "",
        "body_ja": "なぜ起業するのか？それは、私たちが掲げるアプリ構想に十分な採算性と、社会的な価値が認められると判断したからです。\nメッセージ： 挑戦の始まりに、心からの祝福を。",
        "body_en": " Why start a company? Because I have determined that my app concepts have clear commercial viability and significant market potential.\nMessage: Congratulations on this new beginning!",
        "body_de": "",
        "body_fr": "",
        "body_es": ""
    },
    {
        "project_id": "free_call_app",
        "date": "2026.02.12",
        "category": "start",
        "image": "index_phot/freecallapp.png",
        "status": "coming",
        "project_ja": "電話無料APP（FreeCallApp）",
        "project_en": "Free Call App",
        "project_de": "Gratis Anruf-App",
        "project_fr": "App d'appels gratuits",
        "project_es": "App de llamadas gratis",
        "title_ja": "広告を力に、通話を自由に。",
        "title_en": "Powered by ads, call freely.",
        "title_de": "Werbefinanziert, frei telefonieren.",
        "title_fr": "Appels libres grâce à la publicité.",
        "title_es": "Llamadas libres impulsadas por anuncios.",
        "body_ja": "特徴\n・完全無料: 短い動画広告を見るだけで通話時間を獲得。\n・固定電話専用: お店や役所へのちょっとした電話に最適。\n・登録不要: 面倒な会員登録なしですぐに使えます。",
        "body_en": "Features\n・Completely Free: Earn calling time simply by watching short video ads.\n・Fixed-line Exclusive: Perfect for quick calls to shops or public offices.\n・No Registration Required: Start calling immediately without any tedious sign-up process.",
        "body_de": "Eigenschaften\n・Komplett kostenlos: Sammeln Sie Gesprächsminuten, indem Sie sich kurze Videoanzeigen ansehen.\n・Exklusiv für das Festnetz: Ideal für kurze Anrufe in Geschäften oder Behörden.\n・Keine Registrierung erforderlich: Sofort einsatzbereit ohne mühsame Anmeldung.",
        "body_fr": "Caractéristiques\n・Entièrement gratuit : Gagnez du temps d'appel en regardant simplement de courtes publicités vidéo.\n・Exclusivement pour les lignes fixes : Idéal pour les courts appels vers les magasins ou les administrations.\n・Aucune inscription requise : Prêt à l'emploi immédiatement sans inscription fastidieuse.",
        "body_es": "Características\n・Totalmente gratis: Obtén tiempo de llamada simplemente viendo anuncios de video cortos.\n・Exclusivo para teléfonos fijos: Ideal para llamadas cortas a tiendas u oficinas públicas.\n・Sin registro: Úselo al instante sin tediosos procesos de suscripción."
    }
];