const adminMasterData = [
    {
        "project_id": "outgoing_call_widget",
        "date": "2026.02.04",
        "category": "update",
        "image": "index_phot/Outgoing_Call_Widget.png",
        "status": "coming",
        "project_ja": "発信電話ウィジェット",
        "project_en": "Outgoing Call Widget",
        "project_de": "Anruf-Monitor Widget",
        "project_fr": "Widget d'Appels Sortants",
        "project_es": "Widget de Llamadas Salientes",
        "title_ja": "無料通話時間の設定と「ウィジェット」の表示、有料通話の判別完了。",
        "title_en": "Completed the configuration for free call allowances, home screen widget display, and the system to identify paid (non-bundle) calls.",
        "title_de": "Die Konfiguration des Freiminuten-Limits, die Anzeige des Widgets auf dem Home-Bildschirm sowie die Identifizierung kostenpflichtiger Anrufe wurden erfolgreich implementiert.",
        "title_fr": "La configuration du forfait d'appels gratuits, l'affichage du widget sur l'écran d'accueil et le système d'identification des appels payants sont désormais terminés.",
        "title_es": "Se ha completado la configuración del límite de llamadas gratuitas, la visualización del widget en la pantalla de inicio y el sistema para identificar llamadas con costo.",
        "body_ja": "30秒単位の正確な計算とウィジェット表示で、無料通話枠の残り時間を賢く管理。",
        "body_en": "Smartly manage your remaining free call balance with accurate 30-second billing increments and a convenient home screen widget.",
        "body_de": "Verwalten Sie Ihr verbleibendes Freiminuten-Kontingent clever – mit präziser 30-Sekunden-Taktung und praktischer Anzeige direkt auf Ihrem Home-Bildschirm.",
        "body_fr": "Gérez intelligemment le solde de votre forfait d'appels gratuits grâce à un calcul précis par paliers de 30 secondes et un affichage direct sur votre écran d'accueil.",
        "body_es": "Gestione de forma inteligente el saldo restante de su plan gratuito con cálculos precisos en intervalos de 30 segundos y visualización mediante un widget en su pantalla de inicio."
    },
    {
        "project_id": "kei_applab",
        "date": "2026.02.12",
        "category": "start",
        "image": "index_phot/KEI_App_Lab.png",
        "status": "coming",
        "project_ja": "啓(KEI)AppLab",
        "project_en": "KEI AppLab",
        "project_de": "",
        "project_fr": "",
        "project_es": "",
        "title_ja": " この度、屋号として新たな一歩を踏み出し、起業することを決意いたしました。",
        "title_en": " I have officially decided to launch my own business under the trade name KEI AppLab.",
        "title_de": "",
        "title_fr": "",
        "title_es": "",
        "body_ja": "なぜ起業するのか？それは、私たちが掲げるアプリ構想に十分な採算性と、社会的な価値が認められると判断したからです。\nメッセージ： 挑戦の始まりに、心からの祝福を。",
        "body_en": " Why start a company? Because I have determined that my app concepts have clear commercial viability and significant market potential.\nMessage: Congratulations on this new beginning!",
        "body_de": "",
        "body_fr": "",
        "body_es": ""
    },
    {
        "project_id": "free_call_app",
        "date": "2026.02.12",
        "category": "start",
        "image": "index_phot/freecallapp.png",
        "status": "coming",
        "project_ja": "電話無料APP（FreeCallApp）",
        "project_en": "Free Call App",
        "project_de": "Gratis Anruf-App",
        "project_fr": "App d'appels gratuits",
        "project_es": "App de llamadas gratis",
        "title_ja": "広告を力に、通話を自由に。",
        "title_en": "Powered by ads, call freely.",
        "title_de": "Werbefinanziert, frei telefonieren.",
        "title_fr": "Appels libres grâce à la publicité.",
        "title_es": "Llamadas libres impulsadas por anuncios.",
        "body_ja": "特徴\n・完全無料: 短い動画広告を見るだけで通話時間を獲得。\n・固定電話専用: お店や役所へのちょっとした電話に最適。\n・登録不要: 面倒な会員登録なしですぐに使えます。",
        "body_en": "Features\n・Completely Free: Earn calling time simply by watching short video ads.\n・Fixed-line Exclusive: Perfect for quick calls to shops or public offices.\n・No Registration Required: Start calling immediately without any tedious sign-up process.",
        "body_de": "Eigenschaften\n・Komplett kostenlos: Sammeln Sie Gesprächsminuten, indem Sie sich kurze Videoanzeigen ansehen.\n・Exklusiv für das Festnetz: Ideal für kurze Anrufe in Geschäften oder Behörden.\n・Keine Registrierung erforderlich: Sofort einsatzbereit ohne mühsame Anmeldung.",
        "body_fr": "Caractéristiques\n・Entièrement gratuit : Gagnez du temps d'appel en regardant simplement de courtes publicités vidéo.\n・Exclusivement pour les lignes fixes : Idéal pour les courts appels vers les magasins ou les administrations.\n・Aucune inscription requise : Prêt à l'emploi immédiatement sans inscription fastidieuse.",
        "body_es": "Características\n・Totalmente gratis: Obtén tiempo de llamada simplemente viendo anuncios de video cortos.\n・Exclusivo para teléfonos fijos: Ideal para llamadas cortas a tiendas u oficinas públicas.\n・Sin registro: Úselo al instante sin tediosos procesos de suscripción."
    },
    {
        "project_id": "gorila",
        "date": "2026.02.12",
        "category": "update",
        "image": "index_phot/index_play.png",
        "status": "coming",
        "project_ja": "GORIRA",
        "project_en": "GORILA",
        "project_de": "Gratis Anruf-App",
        "project_fr": "App d'appels gratuits",
        "project_es": "App de llamadas gratis",
        "title_ja": "広告を力に、通話を自由に。",
        "title_en": "Powered by ads, call freely.",
        "title_de": "Werbefinanziert, frei telefonieren.",
        "title_fr": "Appels libres grâce à la publicité.",
        "title_es": "Llamadas libres impulsadas por anuncios.",
        "body_ja": "特徴\n・完全無料: 短い動画広告を見るだけで通話時間を獲得。\n・固定電話専用: お店や役所へのちょっとした電話に最適。\n・登録不要: 面倒な会員登録なしですぐに使えます。",
        "body_en": "Features\n・Completely Free: Earn calling time simply by watching short video ads.\n・Fixed-line Exclusive: Perfect for quick calls to shops or public offices.\n・No Registration Required: Start calling immediately without any tedious sign-up process.",
        "body_de": "Eigenschaften\n・Komplett kostenlos: Sammeln Sie Gesprächsminuten, indem Sie sich kurze Videoanzeigen ansehen.\n・Exklusiv für das Festnetz: Ideal für kurze Anrufe in Geschäften oder Behörden.\n・Keine Registrierung erforderlich: Sofort einsatzbereit ohne mühsame Anmeldung.",
        "body_fr": "Caractéristiques\n・Entièrement gratuit : Gagnez du temps d'appel en regardant simplement de courtes publicités vidéo.\n・Exclusivement pour les lignes fixes : Idéal pour les courts appels vers les magasins ou les administrations.\n・Aucune inscription requise : Prêt à l'emploi immédiatement sans inscription fastidieuse.",
        "body_es": "Características\n・Totalmente gratis: Obtén tiempo de llamada simplemente viendo anuncios de video cortos.\n・Exclusivo para teléfonos fijos: Ideal para llamadas cortas a tiendas u oficinas públicas.\n・Sin registro: Úselo al instante sin tediosos procesos de suscripción."
    },
    {
        "project_id": "qqqqq",
        "date": "2026.02.26",
        "category": "update",
        "image": "index_phot/freecallapp.png",
        "status": "coming",
        "privacy_html": "<!DOCTYPE html>\n<html lang=\"ja\">\n<head>\n    <meta charset=\"UTF-8\">\n    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\n    <title>プライバシーポリシー | [アプリ名をここに入力]</title>\n    <style>\n        /* 1. デザイン・レイアウトのルール */\n        body {\n            background-color: #f9f9f9;\n            color: #333;\n            font-family: 'Helvetica Neue', Arial, 'Hiragino Kaku Gothic ProN', 'Hiragino Sans', Meiryo, sans-serif;\n            font-size: 14px;\n            line-height: 1.6;\n            margin: 0;\n            padding: 20px;\n        }\n        .container {\n            max-width: 800px;\n            margin: 0 auto;\n            background-color: #ffffff;\n            border-radius: 8px;\n            box-shadow: 0 4px 12px rgba(0,0,0,0.05);\n            padding: 40px;\n            box-sizing: border-box;\n        }\n        \n        /* 見出しのルール */\n        h1 {\n            font-size: 24px;\n            border-bottom: 2px solid #F39C12;\n            padding-bottom: 10px;\n            margin-top: 0;\n            color: #333;\n        }\n        h2 {\n            font-size: 18px;\n            background-color: #f5f5f5;\n            border-left: 5px solid #F39C12;\n            padding: 10px 15px;\n            margin-top: 35px;\n            color: #333;\n        }\n        h3 {\n            font-size: 16px;\n            color: #555;\n            margin-top: 25px;\n            border-bottom: 1px dashed #eee;\n            padding-bottom: 5px;\n        }\n        \n        /* 強調と装飾のルール */\n        strong {\n            font-weight: bold;\n        }\n        .important {\n            color: #d9534f;\n            font-weight: bold;\n        }\n        \n        /* 文章構成のルール */\n        .date {\n            text-align: right;\n            font-size: 12px;\n            color: #888;\n            margin-bottom: 20px;\n        }\n        p {\n            margin-bottom: 15px;\n        }\n        ul {\n            padding-left: 20px;\n            margin-bottom: 15px;\n        }\n        li {\n            margin-bottom: 8px;\n        }\n        .footer {\n            border-top: 1px solid #eee;\n            text-align: center;\n            font-size: 12px;\n            color: #888;\n            padding-top: 20px;\n            margin-top: 50px;\n        }\n\n        /* スマホ用レスポンシブ */\n        @media (max-width: 600px) {\n            .container {\n                padding: 20px;\n            }\n        }\n    </style>\n</head>\n<body>\n\n<div class=\"container\">\n    <!-- 大見出し -->\n    <h1>プライバシーポリシー</h1>\n    \n    <!-- 制定日 -->\n    <div class=\"date\">\n        制定日：2026年3月XX日<br>\n        啓 App Lab\n    </div>\n\n    <!-- 前文 -->\n    <p>啓 App Lab（以下、「当方」といいます）は、当方が提供するスマートフォン用アプリケーション「[アプリ名をここに入力]」（以下、「本アプリ」といいます）における、ユーザーの個人情報を含む利用者情報の取扱いについて、以下のとおりプライバシーポリシー（以下、「本ポリシー」といいます）を定めます。</p>\n    <p>本アプリのご利用にあたっては、本ポリシーの内容をご確認いただき、同意された場合のみご利用ください。</p>\n\n    <!-- 第1条 -->\n    <h2>第1条（収集する情報および収集方法）</h2>\n    <p>本アプリの提供にあたり、当方は以下の情報を取得・利用する場合があります。</p>\n\n    <h3>1. 通話履歴（発信時間・発信記録）</h3>\n    <p>本アプリは、ユーザーが設定した通話上限時間（例：70分）に対する残りの通話時間を計算し、ウィジェット等に表示するため、端末内の通話履歴へのアクセス権限を使用します。</p>\n    <ul>\n        <li><strong>利用目的：</strong> 有料発信電話の通話時間を監視し、上限時間までの残り時間を算出・表示するため。</li>\n        <li><strong>データの保存・送信：</strong> <span class=\"important\">取得した通話履歴データは、ユーザーの端末内でのみ処理・保存されます。当方や第三者の外部サーバーに送信、収集、または保存されることは一切ありません。</span></li>\n    </ul>\n\n    <h3>2. 端末情報および広告識別子</h3>\n    <p>広告の配信およびアプリの利用状況解析のために、以下の情報を自動的に取得します。</p>\n    <ul>\n        <li>IPアドレス、アクセスログ</li>\n        <li>端末のモデル名、OSバージョン</li>\n        <li>広告識別子（Google Advertising ID、Apple IDFA等）</li>\n    </ul>\n\n    <!-- 第2条 -->\n    <h2>第2条（利用目的およびデータの保存場所）</h2>\n    <p>当方は、取得した利用者情報を以下の目的で利用します。</p>\n    <ul>\n        <li><strong>本サービスの提供：</strong> ユーザーの通話時間を計算し、ウィジェット等を通じて視覚的な目安を提供するため。</li>\n        <li><strong>広告の配信：</strong> ユーザーの興味関心に適したバナー広告等を表示するため。</li>\n        <li><strong>アプリの改善：</strong> 障害発生時のクラッシュログを解析し、品質を向上させるため。</li>\n    </ul>\n    <ul>\n        <li><strong>データの保存場所：</strong> 広告配信や解析のために収集された識別子やIPアドレス等のデータは、当方が利用する提携事業者（Google LLC等）のサーバー（主に米国に所在）にて処理されます。前述の通り、通話履歴自体が外部サーバーに保存されることはありません。</li>\n    </ul>\n\n    <!-- 第3条 -->\n    <h2>第3条（情報収集モジュールとCookieの利用について）</h2>\n    <p>当方は、本アプリの機能提供および広告配信のために、以下の提携事業者の情報収集モジュールを利用しており、必要な範囲で情報が送信されます。</p>\n\n    <h3>1. Google AdMob（広告配信）</h3>\n    <p>本アプリには、上下のバナー広告枠にGoogle AdMobを利用しています。</p>\n    <ul>\n        <li><strong>提供者：</strong> Google LLC</li>\n        <li><strong>Cookie（クッキー）および識別子の利用：</strong> 第三者の広告配信事業者であるGoogleは、Cookieやモバイルデバイスの広告識別子を使用して、ユーザーが過去に本アプリや他のウェブサイト・アプリを利用した際の情報に基づき、パーソナライズされた適切な広告を配信しています。</li>\n        <li><strong>送信される情報：</strong> 広告識別子、IPアドレス、端末情報等</li>\n        <li><strong>オプトアウト：</strong> ユーザーは、端末の広告設定（「広告のパーソナライズをオプトアウト」等）を変更するか、<a href=\"https://policies.google.com/technologies/ads\" target=\"_blank\">Googleの広告設定ページ</a>にアクセスすることで、パーソナライズ広告のためのCookieや識別子の利用を無効にすることができます。</li>\n    </ul>\n\n    <!-- 第4条 -->\n    <h2>第4条（ユーザーの権利：GDPRおよびCCPAへの対応）</h2>\n    <p>当方は、国際的なプライバシー保護規則を尊重し、以下の通り対応します。</p>\n\n    <h3>1. EUおよびEEA圏内のユーザー（GDPR対応）</h3>\n    <p>EU一般データ保護規則（GDPR）に基づき、ユーザーは自身の個人データに関する以下の権利を有します。</p>\n    <ul>\n        <li><strong>アクセス権と訂正権：</strong> 自身に関するどのようなデータが収集されているかを確認し、訂正する権利。</li>\n        <li><strong><span class=\"important\">データを削除する権利（忘れられる権利）：</span></strong> 当方に対し、保存されている個人データの削除を要求する権利。</li>\n        <li><strong>処理の法的根拠：</strong> IPアドレスや広告識別子の処理は、無料でのサービス提供の維持（広告配信）という当方の「正当な利益」、またはユーザーの「同意」を法的根拠として行われます。データの削除や同意の撤回をご希望の場合は、第7条のお問い合わせ窓口までご連絡ください。</li>\n    </ul>\n\n    <h3>2. 米国カリフォルニア州のユーザー（CCPA対応）</h3>\n    <p>カリフォルニア州消費者プライバシー法（CCPA）に基づき、当方はユーザーの個人情報を第三者に販売することはありません。<span class=\"important\">（Do Not Sell My Personal Information）</span></p>\n\n    <!-- 第5条 -->\n    <h2>第5条（免責事項：通話時間の計算について）</h2>\n    <p>本アプリを利用するにあたり、以下の事項をあらかじめご了承ください。</p>\n    <ul>\n        <li><strong>目安としての利用：</strong> 本アプリがウィジェット等で表示する「残りの通話時間」は、端末内に記録された発信履歴を基に算出された目安です。</li>\n        <li><strong><span class=\"important\">通信キャリアとの差異：</span></strong> 実際の通信キャリアの課金システム（呼び出し時間のカウントの有無、秒数の端数切り上げ処理など）の仕様により、本アプリの表示時間と、キャリアからの実際の請求時間にはズレが生じる場合があります。</li>\n        <li><strong><span class=\"important\">損害の免責：</span></strong> 本アプリの計算結果や表示内容に起因して、ユーザーが意図せず通話上限を超過し、追加の通話料金や損害が発生した場合であっても、当方は一切の責任を負いません。最終的な通話時間の確認は、ご契約の通信キャリアの明細等でご自身で行ってください。</li>\n    </ul>\n\n    <!-- 第6条 -->\n    <h2>第6条（プライバシーポリシーの変更）</h2>\n    <p>当方は、法令の改正や事業上の必要性等に応じて、本ポリシーを変更することがあります。重要な変更がある場合には、本アプリ内または公式サイト上で告知します。変更後のポリシーは、本アプリ内または公式サイトに掲載された時点で効力を生じるものとします。</p>\n\n    <!-- 第7条 -->\n    <h2>第7条（お問い合わせ窓口）</h2>\n    <p>本ポリシーおよび利用者情報の取扱い、またはデータの削除要求等に関するお問い合わせは、以下の窓口までご連絡ください。</p>\n    <p>\n        <strong>啓 App Lab (KEI App Lab)</strong><br>\n        Email: support@keiapplab.com\n    </p>\n\n    <!-- フッター -->\n    <div class=\"footer\">\n        &copy; 2026 KEI App Lab. All Rights Reserved.\n    </div>\n</div>\n\n</body>\n</html>",
        "project_ja": "654654654321",
        "project_en": "qqqqq",
        "project_de": "",
        "project_fr": "",
        "project_es": "",
        "title_ja": "654654654",
        "title_en": "",
        "title_de": "",
        "title_fr": "",
        "title_es": "",
        "body_ja": "654654654654",
        "body_en": "",
        "body_de": "",
        "body_fr": "",
        "body_es": ""
    }
];