const indexNewsData = [
    {
        "id": 1771707317374,
        "date": "2026.02.12",
        "category": "start",
        "image": "free_call_app/index.png",
        "link": "free_call_app/index.html",
        "project_ja": "電話無料APP（FreeCallApp）",
        "project_en": "Free Call App",
        "project_de": "Gratis Anruf-App",
        "project_fr": "App d'appels gratuits",
        "project_es": "App de llamadas gratis",
        "title_ja": "広告を力に、通話を自由に。",
        "title_en": "Powered by ads, call freely.",
        "title_de": "Werbefinanziert, frei telefonieren.",
        "title_fr": "Appels libres grâce à la publicité.",
        "title_es": "Llamadas libres impulsadas por anuncios."
    },
    {
        "id": 1771624071689,
        "date": "2026.02.12",
        "category": "start",
        "image": "kei_applab/index.png",
        "link": "kei_applab/index.html",
        "project_ja": "啓(KEI)AppLab",
        "project_en": "KEI AppLab",
        "project_de": "",
        "project_fr": "",
        "project_es": "",
        "title_ja": " この度、屋号として新たな一歩を踏み出し、起業することを決意いたしました。",
        "title_en": " I have officially decided to launch my own business under the trade name KEI AppLab.",
        "title_de": "",
        "title_fr": "",
        "title_es": ""
    },
    {
        "id": 1771552017013,
        "date": "2026.02.03",
        "category": "start",
        "image": "outgoing_call_widget/index.png",
        "link": "outgoing_call_widget/index.html",
        "project_ja": "発信電話ウィジェット",
        "project_en": "Outgoing Call Widget",
        "project_de": "Anruf-Monitor Widget",
        "project_fr": "Widget d'Appels Sortants",
        "project_es": "Salientes",
        "title_ja": "70分等の無料通話時間を管理する「発信電話ウィジェット」の開発を開始しました。\n",
        "title_en": "We have launched the development of the \"Outgoing Call Widget,\" designed to manage free calling plans such as 70-minute bundles.",
        "title_de": "Wir haben mit der Entwicklung des „Anruf-Monitor Widgets“ begonnen, um Freiminuten-Pakete (z. B. 70 Minuten) komfortabel zu verwalten.",
        "title_fr": "Nous avons lancé le développement du « Widget d'Appels Sortants », conçu pour gérer les forfaits d'appels gratuits comme les offres de 70 minutes.",
        "title_es": "Hemos iniciado el desarrollo del \"Widget de Llamadas Salientes\", diseñado para gestionar planes de llamadas gratuitas como el de 70 minutos."
    },
    {
        "id": 1771799136995,
        "date": "2026.02.23",
        "category": "update",
        "image": "kjuhuhuh/index.png",
        "link": "kjuhuhuh/index.html",
        "project_ja": "GORIRA11111",
        "project_en": "kjuhuhuh",
        "project_de": "",
        "project_fr": "",
        "project_es": "",
        "title_ja": "321321321321321",
        "title_en": "",
        "title_de": "",
        "title_fr": "",
        "title_es": ""
    },
    {
        "id": 1771798643235,
        "date": "2026.02.23",
        "category": "update",
        "image": "kjuhuhuh/index.png",
        "link": "kjuhuhuh/index.html",
        "project_ja": "GORIRA11111",
        "project_en": "kjuhuhuh",
        "project_de": "",
        "project_fr": "",
        "project_es": "",
        "title_ja": "321321321321321",
        "title_en": "",
        "title_de": "",
        "title_fr": "",
        "title_es": ""
    },
    {
        "id": 1771774991128,
        "date": "2026.02.23",
        "category": "update",
        "image": "test_gorira/index.png",
        "link": "test_gorira/index.html",
        "project_ja": "ゴリラ",
        "project_en": "test_gorira",
        "project_de": "",
        "project_fr": "",
        "project_es": "",
        "title_ja": "どうなってる？大丈夫？",
        "title_en": "",
        "title_de": "",
        "title_fr": "",
        "title_es": ""
    },
    {
        "id": 1771771114443,
        "date": "2026.02.12",
        "category": "update",
        "image": "gorira/index.png",
        "link": "gorira/index.html",
        "project_ja": "GORIRA",
        "project_en": "GORIRA",
        "project_de": "Gratis Anruf-App",
        "project_fr": "App d'appels gratuits",
        "project_es": "App de llamadas gratis",
        "title_ja": "広告を力に、通話を自由に。",
        "title_en": "Powered by ads, call freely.",
        "title_de": "Werbefinanziert, frei telefonieren.",
        "title_fr": "Appels libres grâce à la publicité.",
        "title_es": "Llamadas libres impulsadas por anuncios."
    },
    {
        "id": 1771764402824,
        "date": "2026.02.12",
        "category": "update",
        "image": "gorira/index.png",
        "link": "gorira/index.html",
        "project_ja": "GORIRA",
        "project_en": "GORIRA",
        "project_de": "Gratis Anruf-App",
        "project_fr": "App d'appels gratuits",
        "project_es": "App de llamadas gratis",
        "title_ja": "広告を力に、通話を自由に。",
        "title_en": "Powered by ads, call freely.",
        "title_de": "Werbefinanziert, frei telefonieren.",
        "title_fr": "Appels libres grâce à la publicité.",
        "title_es": "Llamadas libres impulsadas por anuncios."
    },
    {
        "id": 1771763658579,
        "date": "2026.02.12",
        "category": "update",
        "image": "gorira/index.png",
        "link": "gorira/index.html",
        "project_ja": "GORIRA",
        "project_en": "GORIRA",
        "project_de": "Gratis Anruf-App",
        "project_fr": "App d'appels gratuits",
        "project_es": "App de llamadas gratis",
        "title_ja": "広告を力に、通話を自由に。",
        "title_en": "Powered by ads, call freely.",
        "title_de": "Werbefinanziert, frei telefonieren.",
        "title_fr": "Appels libres grâce à la publicité.",
        "title_es": "Llamadas libres impulsadas por anuncios."
    },
    {
        "id": 1771761345182,
        "date": "2026.02.12",
        "category": "update",
        "image": "gorira/index.png",
        "link": "gorira/index.html",
        "project_ja": "GORIRA",
        "project_en": "GORIRA",
        "project_de": "Gratis Anruf-App",
        "project_fr": "App d'appels gratuits",
        "project_es": "App de llamadas gratis",
        "title_ja": "広告を力に、通話を自由に。",
        "title_en": "Powered by ads, call freely.",
        "title_de": "Werbefinanziert, frei telefonieren.",
        "title_fr": "Appels libres grâce à la publicité.",
        "title_es": "Llamadas libres impulsadas por anuncios."
    },
    {
        "id": 1771595659004,
        "date": "2026.02.04",
        "category": "update",
        "image": "outgoing_call_widget/index.png",
        "link": "outgoing_call_widget/index.html",
        "project_ja": "発信電話ウィジェット",
        "project_en": "Outgoing Call Widget",
        "project_de": "Anruf-Monitor Widget",
        "project_fr": "Widget d'Appels Sortants",
        "project_es": "Widget de Llamadas Salientes",
        "title_ja": "無料通話時間の設定と「ウィジェット」の表示、有料通話の判別完了。",
        "title_en": "Completed the configuration for free call allowances, home screen widget display, and the system to identify paid (non-bundle) calls.",
        "title_de": "Die Konfiguration des Freiminuten-Limits, die Anzeige des Widgets auf dem Home-Bildschirm sowie die Identifizierung kostenpflichtiger Anrufe wurden erfolgreich implementiert.",
        "title_fr": "La configuration du forfait d'appels gratuits, l'affichage du widget sur l'écran d'accueil et le système d'identification des appels payants sont désormais terminés.",
        "title_es": "Se ha completado la configuración del límite de llamadas gratuitas, la visualización del widget en la pantalla de inicio y el sistema para identificar llamadas con costo."
    }
];