// このファイルは admin.html で生成されました
const adminMasterData = [
    {
        "id": 1771442705419,
        "date": "2026.02.19",
        "category": "update",
        "image": "index_phot/index_play.png",
        "project": "ゴリラクリニック",
        "title": "ゴリラが経営するちょっと怖いけど、本当は心優しいシルバーバックのおじさん。",
        "body": "ゴリラって何種類いるか知っていますか？生息地を負われ絶滅寸前。彼らは心優しきＢ型のゴリラさん。植物しか食べないのに全身筋肉の凄い奴。",
        "project_en": "",
        "title_en": "",
        "body_en": "",
        "project_de": "",
        "title_de": "",
        "body_de": "",
        "project_fr": "",
        "title_fr": "",
        "body_fr": "",
        "project_es": "",
        "title_es": "",
        "body_es": ""
    },
    {
        "id": 1771404678022,
        "date": "2026.02.18",
        "category": "update",
        "image": "index_phot/index_play.png",
        "project": "起業",
        "title": "とうとう始まったやばいぞやばいぞ！起業なんだよ。あああああああああ～なんてことだ。こんな時が来るなんて。。。",
        "body": "とうとう始まったんだよ。すげえだろ！\n成功するか分からないけど、夢が詰まってる。\nお互いの弱い部分をお互いが補って、やばいチームって感じ！\n飛び出てるぞミニゲーム",
        "project_en": "start-up",
        "title_en": "It's finally started—this is bad, really bad! I'm starting a business.",
        "body_en": "It's finally started. Isn't it awesome?!\nNo telling if it'll work out, but it's packed with dreams.\nWe cover each other's weaknesses—feels like a killer team!\nHere comes the mini-game!",
        "project_de": "Gründung eines Unternehmens",
        "title_de": "Es hat endlich begonnen, verdammt noch mal! Die Gründung eines Unternehmens, sage ich euch.",
        "body_de": "Es hat endlich begonnen. Ziemlich verdammt genial, oder?\nKeine Ahnung, ob es Erfolg haben wird, aber es steckt voller Träume.\nWir ergänzen uns gegenseitig in unseren Stärken, und ja, das Team\nkommt jetzt richtig in Fahrt. Minispiel",
        "project_fr": "Esprit d'entreprise",
        "title_fr": "Ça y est, c'est parti, ça va être grave, ça va être grave ! C'est le lancement de mon entreprise.",
        "body_fr": "Ça a enfin commencé. C'est génial, non ?\nJe ne sais pas si ça va marcher, mais c'est un rêve qui prend forme.\nOn compense nos faiblesses respectives, ça va être une équipe de ouf !\nÇa va déchirer, les mini-jeux !",
        "project_es": "Imprenditorialità",
        "title_es": "Finalmente è iniziato, maledizione, maledizione! Avviare un'impresa, ve lo dico io.",
        "body_es": "Finalmente è iniziato. Fantastico, vero?\nNon si sa se avrà successo, ma è pieno di sogni.\nCi copriamo a vicenda le debolezze: sembra proprio una squadra perfetta!\nCi siamo, mini-gioco!"
    },
    {
        "id": 1771339740409,
        "date": "2026.02.17",
        "category": "start",
        "image": "index_phot/index_play.png",
        "project": "テストプロジェクト",
        "title": "テストのお知らせ。そうテストだよ。",
        "body": "カテゴリや画像有無の条件（透明化）に関わらず、入力されたテキストや画像が常にカードに反映されるようにしました。",
        "project_en": "",
        "title_en": "",
        "body_en": "",
        "project_de": "",
        "title_de": "",
        "body_de": "",
        "project_fr": "",
        "title_fr": "",
        "body_fr": "",
        "project_es": "",
        "title_es": "",
        "body_es": ""
    },
    {
        "id": 1771326215208,
        "date": "2026.02.17",
        "category": "update",
        "image": "index_phot/index_play.png",
        "project": "起業",
        "title": "とうとう始まったやばいぞやばいぞ！起業なんだよ。",
        "body": "とうとう始まったんだよ。すげえだろ！\n成功するか分からないけど、夢が詰まってる。\nお互いの弱い部分をお互いが補って、やばいチームって感じ！\n飛び出てるぞミニゲーム",
        "project_en": "start-up",
        "title_en": "It's finally started—this is bad, really bad! I'm starting a business.",
        "body_en": "It's finally started. Isn't it awesome?!\nNo telling if it'll work out, but it's packed with dreams.\nWe cover each other's weaknesses—feels like a killer team!\nHere comes the mini-game!",
        "project_de": "Gründung eines Unternehmens",
        "title_de": "Es hat endlich begonnen, verdammt noch mal! Die Gründung eines Unternehmens, sage ich euch.",
        "body_de": "Es hat endlich begonnen. Ziemlich verdammt genial, oder?\nKeine Ahnung, ob es Erfolg haben wird, aber es steckt voller Träume.\nWir ergänzen uns gegenseitig in unseren Stärken, und ja, das Team\nkommt jetzt richtig in Fahrt. Minispiel",
        "project_fr": "Esprit d'entreprise",
        "title_fr": "Ça y est, c'est parti, ça va être grave, ça va être grave ! C'est le lancement de mon entreprise.",
        "body_fr": "Ça a enfin commencé. C'est génial, non ?\nJe ne sais pas si ça va marcher, mais c'est un rêve qui prend forme.\nOn compense nos faiblesses respectives, ça va être une équipe de ouf !\nÇa va déchirer, les mini-jeux !",
        "project_es": "Imprenditorialità",
        "title_es": "Finalmente è iniziato, maledizione, maledizione! Avviare un'impresa, ve lo dico io.",
        "body_es": "Finalmente è iniziato. Fantastico, vero?\nNon si sa se avrà successo, ma è pieno di sogni.\nCi copriamo a vicenda le debolezze: sembra proprio una squadra perfetta!\nCi siamo, mini-gioco!"
    },
    {
        "id": 1771271575656,
        "date": "2026.02.17",
        "category": "release",
        "project": "ごちです。",
        "title": "きた～どうだ～。まじなんです。うそ～。",
        "body": "そんなこともあるよね。\nだがしかし、なにがや！\nそやかし～、わしも武士の端くれ輩の～",
        "projectEn": "",
        "titleEn": "",
        "bodyEn": "",
        "image": "index_about.png"
    },
    {
        "date": "2026.02.04",
        "category": "press",
        "title_ja": "発信通話管理APP",
        "title_en": "CallDurationMonitor",
        "url": "#",
        "image": ""
    }
];
